tasks:
  - init: npm install
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
    - esbenp.prettier-vscode@3.18.0:SpDMXXww8cAUOXaBCNECgQ==
    - ritwickdey.live-sass@3.0.0:x2c+sCJm+QmH2qn2h1X9Zw==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - eamodio.gitlens@10.2.0:L4GfuK5a2eOIpfcKVVvjEw==